### ISSUE TITLE
[Style] 사용성 개선하기

### ISSUE THREAD

**Issue by coddingyun** [YEONDOO-swm/YEONDOO-fe#197]
## Description
사용성 개선을 위해 워크스페이스 홈과 대시보드 바꾸기

## Todo
- [x] 워크스페이스 홈과 대시보드 바꾸기
- [x] 대시보드 사이드바 색깔 바꾸기
- [x] 검색창 더 잘 보이게 하기
- [x] 추천 섹션과 recently Study Paper 구분하기
- [x] Study with AI에서 (Start) Study! 로 심플하게 바꾸기
- [x] 사이드바의 Workspaces -> Home으로 바꾸기
- [x] More -> Study with AI로 바꾸기
