### ISSUE TITLE
Amplitude 연동

### ISSUE THREAD

**Issue by coddingyun** [YEONDOO-swm/YEONDOO-fe#2]
## Description
유저의 액션을 트래킹할 수 있는 도구, amplitude를 프로젝트에 연결시킨다. 

## Todo
- [x] Amplitude 프로젝트 생성
- [x] 프로젝트 코드 추가
- [x] 트래킹이 잘 되는지 확인
- [x] 프로젝트에 팀원 추가

## Note
안되면 오은석 멘토님께!
